"""added images

Revision ID: a3f37045f936
Revises: 1f2462567e00
Create Date: 2024-04-17 20:15:05.120181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f37045f936'
down_revision = '1f2462567e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_blob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_blob', sa.BLOB(), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
